### ISSUE TITLE
Sphinx 3.5.3 on Python 3.10 broken

### ISSUE THREAD

**Issue by dopplershift** [conda-forge/sphinx-feedstock#110]
Installing Sphinx on Python 3.10 from conda-forge right now results in installing Sphinx 3.5.3 together with docutils 0.18. With this combination, running `sphinx-build` gives:
```
❯ sphinx-build
Traceback (most recent call last):
  File "/Users/rmay/miniconda3/envs/py310/bin/sphinx-build", line 6, in <module>
    from sphinx.cmd.build import main
  File "/Users/rmay/miniconda3/envs/py310/lib/python3.10/site-packages/sphinx/cmd/build.py", line 25, in <module>
    from sphinx.application import Sphinx
  File "/Users/rmay/miniconda3/envs/py310/lib/python3.10/site-packages/sphinx/application.py", line 32, in <module>
    from sphinx.config import Config
  File "/Users/rmay/miniconda3/envs/py310/lib/python3.10/site-packages/sphinx/config.py", line 23, in <module>
    from sphinx.util import logging
  File "/Users/rmay/miniconda3/envs/py310/lib/python3.10/site-packages/sphinx/util/__init__.py", line 35, in <module>
    from sphinx.util import smartypants  # noqa
  File "/Users/rmay/miniconda3/envs/py310/lib/python3.10/site-packages/sphinx/util/smartypants.py", line 33, in <module>
    from sphinx.util.docutils import __version_info__ as docutils_version
  File "/Users/rmay/miniconda3/envs/py310/lib/python3.10/site-packages/sphinx/util/docutils.py", line 31, in <module>
    from sphinx.util.typing import RoleFunction
  File "/Users/rmay/miniconda3/envs/py310/lib/python3.10/site-packages/sphinx/util/typing.py", line 34, in <module>
    from types import Union as types_Union
ImportError: cannot import name 'Union' from 'types' (/Users/rmay/miniconda3/envs/py310/lib/python3.10/types.py)
```

Obviously this is broken and a dependency needs to be changed, but I'm not clear what one.

**Comment by dopplershift** [comment]
Will be fixed by patching repodata: https://github.com/conda-forge/conda-forge-repodata-patches-feedstock/pull/181

**Comment by jakirkham** [comment]
Is there any additional follow up needed here Ryan? Or did the repodata patch fix this?

**Comment by dopplershift** [comment]
Sphinx is no longer installable on Python 3.10 with docutils 0.18...so, yay? 😉
